### ISSUE TITLE
Homepage - Secondary links

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#429]
## Outcome

The secondary links on the Homepage to include all relevant destinations

## Scope

- [x] For each link, provide:
  - URL
  - Label
  - Icon from this list: https://starlight.astro.build/guides/components/#icon
  - Type (primary, secondary, minimal)

**Comment by andij** [comment]
I've included the following action links:

```
  actions:
    - text: Introduction
      link: /introduction/
      icon: document
      variant: primary
    - text: Send us feedback
      link: https://forms.office.com/e/LNS9bNnQpp?origin=lprLink
      icon: external
      variant: secondary
    - text: Our process
      link: /guidelines/process/
      icon: laptop
      variant: secondary
```

### Result

![beta nucleus design](https://github.com/centrica-engineering/nucleus-docs/assets/28779/b6434094-2378-4e46-b61c-de5ed61a5fb7)

### Reference

https://github.com/centrica-engineering/nucleus-docs/blob/astro-docs/src/content/docs/index.mdx#L12-L24
